In [16]:
import pandas as pd
import numpy as np

# Question 1
What's the version of Pandas that you installed?

In [3]:
pd.__version__

'2.0.3'

In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-18 16:37:35--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1,4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1,36M  1,71MB/s    in 0,8s    

2023-09-18 16:37:36 (1,71 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [4]:
df = pd.read_csv('housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

## Question 2
How many columns are in the dataset?

In [5]:
print(len(df.columns))

10


# Question 3
Which columns in the dataset have missing values?

In [6]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

# Question 4
How many unique values does the ocean_proximity column have?

In [7]:
print(df['ocean_proximity'].nunique())

5


# Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [8]:
print(df['median_house_value'].mean())

206855.81690891474


# Question 6

    Calculate the average of total_bedrooms column in the dataset.
    Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
    Now, calculate the average of total_bedrooms again.
    Has it changed?

In [14]:
print("Total Bedroom Average before fill missing value: {}".format(df['total_bedrooms'].mean()))

print("Total Bedroom Average after fill missing value: {}".format(df['total_bedrooms'].fillna(df['total_bedrooms'].mean()).mean()))



Total Bedroom Average before fill missing value: 537.8705525375618
Total Bedroom Average after fill missing value: 537.8705525375617


# Question 7

    Select all the options located on islands.
    Select only columns housing_median_age, total_rooms, total_bedrooms.
    Get the underlying NumPy array. Let's call it X.
    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    Compute the inverse of XTX.
    Create an array y with values [950, 1300, 800, 1000, 1300].
    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    What's the value of the last element of w?


In [32]:
X = np.array(df[['housing_median_age', 'total_rooms', 'total_bedrooms']])
print(X)

X_T = X.T
XTX = np.dot(X_T, X)
inv_XTX = np.linalg.inv(XTX)
print(inv_XTX)

y = np.array([950, 1300, 800, 1000, 1300])
w = np.dot(np.dot(inv_XTX, X.T), y)
print(w)


[[  41.  880.  129.]
 [  21. 7099. 1106.]
 [  52. 1467.  190.]
 ...
 [  17. 2254.  485.]
 [  18. 1860.  409.]
 [  16. 2785.  616.]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


ValueError: shapes (3,20640) and (5,) not aligned: 20640 (dim 1) != 5 (dim 0)